/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exempluinterfataprolog;

import exempluinterfataprolog.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Point;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.border.AbstractBorder;

/**
 *
 * @author Lenovo
 */

public class FereastraMea extends javax.swing.JFrame {

    /**
     * Creates new form FereastraMea
     */
    ConexiuneProlog conexiune;
    List<Solutie> solutii;
    int solutieAfisata;
    //Intrebare_intrebatoare panou_intrebari;


    public FereastraMea(String exemplu_Interfata_Prolog) {
       // panou_intrebari = new Intrebare_intrebatoare();
        super(exemplu_Interfata_Prolog);
        initComponents();
        this.setIconImage(new ImageIcon("logo_white.png").getImage());
        pagini = new ArrayList<>();
        pagini.add(Start);
        pagini.add(Expertino);
        pagini.add(panou_intrebare);
        pagini.add(panou_solutie);
        pagini.add(panou_rezultat);
        pagini.add(panou_cum);
        pagini.add(panou_fara_rezultate);
        pagini.add(panou_de_ce);
        pagini.add(panou_afiseaza_fapte);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel9 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Start = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fisierDescrieri = new javax.swing.JTextField();
        alegeFisierDescrieri = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        fisierConstrangeri = new javax.swing.JTextField();
        alegeFisierConstrangeri = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fisierReguli = new javax.swing.JTextField();
        alegeFisierReguli = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        incarcaToateFisierele = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        rezolvaTestul = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Expertino = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        saIncepem = new javax.swing.JButton();
        panou_intrebare = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        text_intrebare = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        iesire = new javax.swing.JButton();
        jPanel29 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        variante = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        adaugaFactor = new javax.swing.JLabel();
        intervalFactor = new javax.swing.JSpinner();
        jPanel44 = new javax.swing.JPanel();
        de_ce_logo = new javax.swing.JLabel();
        panou_rezultat = new javax.swing.JPanel();
        status_rezultat = new javax.swing.JLabel();
        afiseaza_rezultate = new javax.swing.JButton();
        numar_rezultate = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panou_solutie = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        nume = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        factorCertitudine = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        grupa = new javax.swing.JLabel();
        varsta = new javax.swing.JLabel();
        zodie = new javax.swing.JLabel();
        hobby = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descriere_solutie = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        previous = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        next = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        cum = new javax.swing.JButton();
        fapte = new javax.swing.JButton();
        refaTestul = new javax.swing.JButton();
        panou_cum = new javax.swing.JPanel();
        cum_nume = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cum_demonstratie = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panou_fara_rezultate = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        revinoLaMeniu = new javax.swing.JButton();
        jPanel42 = new javax.swing.JPanel();
        panou_de_ce = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        text_de_ce = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        panou_afiseaza_fapte = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        text_afiseaza_fapte = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 0));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/semn_intrebare.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setPreferredSize(new java.awt.Dimension(1300, 800));
        getContentPane().setLayout(new java.awt.CardLayout());

        Start.setBackground(new java.awt.Color(0, 102, 102));
        Start.setLayout(new javax.swing.BoxLayout(Start, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel19.setBackground(new java.awt.Color(51, 51, 51));
        jPanel19.setLayout(new java.awt.GridBagLayout());

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fisierul cu descrieri");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel19.add(jLabel6, gridBagConstraints);

        fisierDescrieri.setBackground(new java.awt.Color(51, 51, 51));
        fisierDescrieri.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        fisierDescrieri.setForeground(new java.awt.Color(255, 255, 255));
        fisierDescrieri.setText("'solutii_se.txt'");
        fisierDescrieri.setBorder(null);
        fisierDescrieri.setCaretColor(new java.awt.Color(255, 255, 255));
        fisierDescrieri.setPreferredSize(new java.awt.Dimension(100, 19));
        fisierDescrieri.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        fisierDescrieri.setSelectionColor(new java.awt.Color(255, 255, 255));
        fisierDescrieri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fisierDescrieriActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 94;
        jPanel19.add(fisierDescrieri, gridBagConstraints);

        alegeFisierDescrieri.setBackground(new java.awt.Color(255, 255, 255));
        alegeFisierDescrieri.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        alegeFisierDescrieri.setText("Alege");
        alegeFisierDescrieri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alegeFisierDescrieriActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel19.add(alegeFisierDescrieri, gridBagConstraints);

        jPanel20.setBackground(new java.awt.Color(51, 51, 51));
        jPanel20.setMinimumSize(new java.awt.Dimension(0, 60));
        jPanel20.setPreferredSize(new java.awt.Dimension(250, 60));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel19.add(jPanel20, gridBagConstraints);

        jPanel21.setBackground(new java.awt.Color(51, 51, 51));
        jPanel21.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel19.add(jPanel21, gridBagConstraints);

        jPanel16.add(jPanel19, java.awt.BorderLayout.PAGE_START);

        jPanel17.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fisierul cu constrangeri");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel13.add(jLabel5, gridBagConstraints);

        fisierConstrangeri.setBackground(new java.awt.Color(51, 51, 51));
        fisierConstrangeri.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        fisierConstrangeri.setForeground(new java.awt.Color(255, 255, 255));
        fisierConstrangeri.setText("'constrangeri_se.txt'");
        fisierConstrangeri.setBorder(null);
        fisierConstrangeri.setCaretColor(new java.awt.Color(255, 255, 255));
        fisierConstrangeri.setPreferredSize(new java.awt.Dimension(100, 19));
        fisierConstrangeri.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        fisierConstrangeri.setSelectionColor(new java.awt.Color(255, 255, 255));
        fisierConstrangeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fisierConstrangeriActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 94;
        jPanel13.add(fisierConstrangeri, gridBagConstraints);

        alegeFisierConstrangeri.setBackground(new java.awt.Color(255, 255, 255));
        alegeFisierConstrangeri.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        alegeFisierConstrangeri.setText("Alege");
        alegeFisierConstrangeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alegeFisierConstrangeriActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel13.add(alegeFisierConstrangeri, gridBagConstraints);

        jPanel14.setBackground(new java.awt.Color(51, 51, 51));
        jPanel14.setMinimumSize(new java.awt.Dimension(0, 60));
        jPanel14.setPreferredSize(new java.awt.Dimension(250, 60));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel13.add(jPanel14, gridBagConstraints);

        jPanel18.setBackground(new java.awt.Color(51, 51, 51));
        jPanel18.setMinimumSize(new java.awt.Dimension(20, 20));
        jPanel18.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel13.add(jPanel18, gridBagConstraints);

        jPanel6.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fisierul cu reguli");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel7.add(jLabel4, gridBagConstraints);

        fisierReguli.setBackground(new java.awt.Color(51, 51, 51));
        fisierReguli.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        fisierReguli.setForeground(new java.awt.Color(255, 255, 255));
        fisierReguli.setText("'reguli_se_2.txt'");
        fisierReguli.setBorder(null);
        fisierReguli.setCaretColor(new java.awt.Color(255, 255, 255));
        fisierReguli.setPreferredSize(new java.awt.Dimension(133, 19));
        fisierReguli.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        fisierReguli.setSelectionColor(new java.awt.Color(255, 255, 255));
        fisierReguli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fisierReguliActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel7.add(fisierReguli, gridBagConstraints);

        alegeFisierReguli.setBackground(new java.awt.Color(255, 255, 255));
        alegeFisierReguli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        alegeFisierReguli.setText("Alege");
        alegeFisierReguli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alegeFisierReguliActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel7.add(alegeFisierReguli, gridBagConstraints);

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setMinimumSize(new java.awt.Dimension(20, 30));
        jPanel11.setPreferredSize(new java.awt.Dimension(20, 30));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel7.add(jPanel11, gridBagConstraints);

        jPanel15.setBackground(new java.awt.Color(51, 51, 51));
        jPanel15.setMinimumSize(new java.awt.Dimension(0, 40));
        jPanel15.setPreferredSize(new java.awt.Dimension(100, 40));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        jPanel7.add(jPanel15, gridBagConstraints);

        jPanel3.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jPanel3, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/settings.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel5.add(jLabel1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Setări");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel5.add(jLabel3, gridBagConstraints);

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setMinimumSize(new java.awt.Dimension(20, 0));
        jPanel10.setPreferredSize(new java.awt.Dimension(20, 100));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel5.add(jPanel10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jPanel5, gridBagConstraints);

        jPanel26.setBackground(new java.awt.Color(51, 51, 51));
        jPanel26.setLayout(new java.awt.GridBagLayout());

        jPanel33.setBackground(new java.awt.Color(51, 51, 51));
        jPanel33.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel26.add(jPanel33, gridBagConstraints);

        incarcaToateFisierele.setBackground(new java.awt.Color(255, 255, 255));
        incarcaToateFisierele.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        incarcaToateFisierele.setForeground(new java.awt.Color(51, 51, 51));
        incarcaToateFisierele.setText("Incarca Fisierele");
        incarcaToateFisierele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incarcaToateFisiereleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel26.add(incarcaToateFisierele, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jPanel26, gridBagConstraints);

        Start.add(jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setLayout(new java.awt.GridBagLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/couple.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel23.add(jLabel7, gridBagConstraints);

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 153));
        jLabel8.setText("Iubirea visurilor tale poate fi mai aproape decat te astepti...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel22.add(jLabel8, gridBagConstraints);

        rezolvaTestul.setBackground(new java.awt.Color(153, 0, 153));
        rezolvaTestul.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rezolvaTestul.setForeground(new java.awt.Color(255, 255, 255));
        rezolvaTestul.setText("Rezolva testul");
        rezolvaTestul.setEnabled(false);
        rezolvaTestul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rezolvaTestulActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        jPanel22.add(rezolvaTestul, gridBagConstraints);

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setMinimumSize(new java.awt.Dimension(0, 50));
        jPanel24.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel22.add(jPanel24, gridBagConstraints);

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setMinimumSize(new java.awt.Dimension(0, 20));
        jPanel25.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel22.add(jPanel25, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel23.add(jPanel22, gridBagConstraints);

        jPanel8.add(jPanel23, java.awt.BorderLayout.PAGE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel4.add(jPanel8, gridBagConstraints);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("CTI isi da intalniri");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel9.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel4.add(jPanel9, gridBagConstraints);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/logo_purple.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel4.add(jLabel26, gridBagConstraints);

        Start.add(jPanel4);

        getContentPane().add(Start, "card2");

        Expertino.setBackground(new java.awt.Color(255, 255, 255));
        Expertino.setLayout(new java.awt.GridBagLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/expertus_mic.png"))); // NOI18N
        jLabel10.setToolTipText("");
        Expertino.add(jLabel10, new java.awt.GridBagConstraints());

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 102));
        jLabel12.setText("El este Expertus,");
        jPanel27.add(jLabel12, java.awt.BorderLayout.CENTER);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 102));
        jLabel11.setText("el te va ajuta sa-ti gasesti perechea..");
        jPanel27.add(jLabel11, java.awt.BorderLayout.PAGE_END);

        Expertino.add(jPanel27, new java.awt.GridBagConstraints());

        saIncepem.setBackground(new java.awt.Color(153, 0, 153));
        saIncepem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        saIncepem.setForeground(new java.awt.Color(255, 255, 255));
        saIncepem.setText("Sa incepem!");
        saIncepem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saIncepemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        Expertino.add(saIncepem, gridBagConstraints);

        getContentPane().add(Expertino, "card4");

        panou_intrebare.setLayout(new javax.swing.BoxLayout(panou_intrebare, javax.swing.BoxLayout.Y_AXIS));

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setMinimumSize(new java.awt.Dimension(1120, 150));
        jPanel30.setName(""); // NOI18N
        jPanel30.setPreferredSize(new java.awt.Dimension(1120, 150));
        jPanel30.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 220));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 220));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel31.setMinimumSize(new java.awt.Dimension(650, 180));
        jPanel31.setName(""); // NOI18N
        jPanel31.setPreferredSize(new java.awt.Dimension(650, 180));
        jPanel31.setRequestFocusEnabled(false);
        jPanel31.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(166, 96));

        text_intrebare.setEditable(false);
        text_intrebare.setBackground(new java.awt.Color(51, 51, 51));
        text_intrebare.setColumns(20);
        text_intrebare.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 29)); // NOI18N
        text_intrebare.setForeground(new java.awt.Color(255, 255, 255));
        text_intrebare.setLineWrap(true);
        text_intrebare.setRows(2);
        text_intrebare.setWrapStyleWord(true);
        jScrollPane2.setViewportView(text_intrebare);

        jPanel31.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jPanel31, gridBagConstraints);

        AbstractBorder myBorder = new TextBubbleBorder(new java.awt.Color(51, 51, 51), 2, 16, 16, true); jPanel1.setBorder(myBorder);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel30.add(jPanel1, gridBagConstraints);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/expertus_mic_mic_mic.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel30.add(jLabel13, gridBagConstraints);

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setMinimumSize(new java.awt.Dimension(170, 250));
        jPanel28.setPreferredSize(new java.awt.Dimension(170, 250));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel30.add(jPanel28, gridBagConstraints);

        iesire.setBackground(new java.awt.Color(153, 0, 153));
        iesire.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        iesire.setForeground(new java.awt.Color(255, 255, 255));
        iesire.setText("iesire");
        iesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iesireActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel30.add(iesire, gridBagConstraints);

        panou_intrebare.add(jPanel30);

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setMinimumSize(new java.awt.Dimension(1250, 0));
        jPanel29.setPreferredSize(new java.awt.Dimension(1250, 0));
        jPanel29.setLayout(new java.awt.GridBagLayout());

        jPanel32.setMinimumSize(new java.awt.Dimension(850, 250));
        jPanel32.setPreferredSize(new java.awt.Dimension(850, 250));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setMaximumSize(new java.awt.Dimension(850, 32767));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(850, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(850, 200));

        variante.setBackground(new java.awt.Color(255, 255, 255));
        variante.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        variante.setAutoscrolls(true);
        variante.setMaximumSize(new java.awt.Dimension(850, 2000));
        variante.setLayout(new javax.swing.BoxLayout(variante, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(variante);

        jPanel32.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel29.add(jPanel32, gridBagConstraints);

        jPanel43.setBackground(new java.awt.Color(255, 255, 255));
        jPanel43.setLayout(new java.awt.GridBagLayout());

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel25.setText("Adauga un factor de certitudine raspunsului:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel43.add(jLabel25, gridBagConstraints);

        adaugaFactor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/add_icon.png"))); // NOI18N
        adaugaFactor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adaugaFactorMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel43.add(adaugaFactor, gridBagConstraints);

        intervalFactor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        intervalFactor.setModel(new javax.swing.SpinnerNumberModel(100, 0, 100, 1));
        intervalFactor.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel43.add(intervalFactor, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel29.add(jPanel43, gridBagConstraints);

        jPanel44.setMinimumSize(new java.awt.Dimension(0, 70));
        jPanel44.setPreferredSize(new java.awt.Dimension(0, 70));

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel29.add(jPanel44, gridBagConstraints);

        de_ce_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/semn_intrebare_2.png"))); // NOI18N
        de_ce_logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                de_ce_logoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel29.add(de_ce_logo, gridBagConstraints);

        panou_intrebare.add(jPanel29);

        getContentPane().add(panou_intrebare, "card3");

        panou_rezultat.setBackground(new java.awt.Color(255, 255, 255));
        panou_rezultat.setLayout(new java.awt.GridBagLayout());

        status_rezultat.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        status_rezultat.setForeground(new java.awt.Color(102, 0, 102));
        status_rezultat.setText("Zilele tale de singuratate au luat sfarsit!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 20;
        panou_rezultat.add(status_rezultat, gridBagConstraints);

        afiseaza_rezultate.setBackground(new java.awt.Color(153, 0, 153));
        afiseaza_rezultate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        afiseaza_rezultate.setForeground(new java.awt.Color(255, 255, 255));
        afiseaza_rezultate.setText("Vezi rezultatele");
        afiseaza_rezultate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afiseaza_rezultateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        panou_rezultat.add(afiseaza_rezultate, gridBagConstraints);

        numar_rezultate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 150)); // NOI18N
        numar_rezultate.setForeground(new java.awt.Color(0, 204, 102));
        numar_rezultate.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        panou_rezultat.add(numar_rezultate, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 51));
        jLabel15.setText("rezultate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        panou_rezultat.add(jLabel15, gridBagConstraints);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/expertus_mic_mic.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panou_rezultat.add(jLabel14, gridBagConstraints);

        getContentPane().add(panou_rezultat, "card6");

        panou_solutie.setBackground(new java.awt.Color(255, 255, 255));
        panou_solutie.setLayout(new java.awt.GridBagLayout());

        jPanel34.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, java.awt.SystemColor.controlHighlight));
        jPanel34.setPreferredSize(new java.awt.Dimension(300, 350));
        jPanel34.setLayout(new java.awt.BorderLayout());

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/profile.png"))); // NOI18N
        jPanel34.add(icon, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panou_solutie.add(jPanel34, gridBagConstraints);

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setPreferredSize(new java.awt.Dimension(500, 350));
        jPanel35.setLayout(new java.awt.GridBagLayout());

        nume.setFont(new java.awt.Font("Century Gothic", 1, 45)); // NOI18N
        nume.setForeground(new java.awt.Color(102, 0, 102));
        nume.setText("Prenume Nume");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel35.add(nume, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 0, 102));
        jLabel16.setText("grupa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel35.add(jLabel16, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 102));
        jLabel17.setText("vârstă");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel35.add(jLabel17, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 102));
        jLabel18.setText("zodie");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel35.add(jLabel18, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 0, 102));
        jLabel19.setText("hobby-uri");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel35.add(jLabel19, gridBagConstraints);

        factorCertitudine.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        factorCertitudine.setText("fc%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel35.add(factorCertitudine, gridBagConstraints);

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setPreferredSize(new java.awt.Dimension(50, 30));

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel35.add(jPanel39, gridBagConstraints);

        grupa.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        grupa.setText("<grupa>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel35.add(grupa, gridBagConstraints);

        varsta.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        varsta.setText("<varsta>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel35.add(varsta, gridBagConstraints);

        zodie.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        zodie.setText("<zodie>");
        zodie.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel35.add(zodie, gridBagConstraints);

        hobby.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        hobby.setText("<hobby>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel35.add(hobby, gridBagConstraints);

        panou_solutie.add(jPanel35, new java.awt.GridBagConstraints());

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel36.setPreferredSize(new java.awt.Dimension(900, 250));
        jPanel36.setLayout(new java.awt.GridBagLayout());

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel41.setPreferredSize(new java.awt.Dimension(650, 200));
        jPanel41.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jScrollPane3.setBorder(null);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(575, 149));

        descriere_solutie.setEditable(false);
        descriere_solutie.setColumns(20);
        descriere_solutie.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        descriere_solutie.setForeground(new java.awt.Color(51, 51, 51));
        descriere_solutie.setLineWrap(true);
        descriere_solutie.setRows(5);
        descriere_solutie.setWrapStyleWord(true);
        jScrollPane3.setViewportView(descriere_solutie);

        jPanel41.add(jScrollPane3);

        AbstractBorder myBorder2 = new TextBubbleBorder(new java.awt.Color(51, 51, 51), 2, 16, 16, false); jPanel41.setBorder(myBorder2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel36.add(jPanel41, gridBagConstraints);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/expertus_mic_mic.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel36.add(jLabel23, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panou_solutie.add(jPanel36, gridBagConstraints);

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setLayout(new java.awt.GridBagLayout());

        previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/back.png"))); // NOI18N
        previous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        jPanel37.add(previous, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panou_solutie.add(jPanel37, gridBagConstraints);

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setLayout(new java.awt.GridBagLayout());

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/forward.png"))); // NOI18N
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        jPanel38.add(next, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panou_solutie.add(jPanel38, gridBagConstraints);

        jPanel40.setBackground(new java.awt.Color(255, 255, 255));
        jPanel40.setPreferredSize(new java.awt.Dimension(300, 50));

        cum.setBackground(new java.awt.Color(153, 0, 153));
        cum.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        cum.setForeground(new java.awt.Color(255, 255, 255));
        cum.setText("cum?");
        cum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cumActionPerformed(evt);
            }
        });
        jPanel40.add(cum);

        fapte.setBackground(new java.awt.Color(153, 0, 153));
        fapte.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        fapte.setForeground(new java.awt.Color(255, 255, 255));
        fapte.setText("fapte");
        fapte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fapteActionPerformed(evt);
            }
        });
        jPanel40.add(fapte);

        refaTestul.setBackground(new java.awt.Color(153, 0, 153));
        refaTestul.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        refaTestul.setForeground(new java.awt.Color(255, 255, 255));
        refaTestul.setText("refa testul");
        refaTestul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refaTestulActionPerformed(evt);
            }
        });
        jPanel40.add(refaTestul);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panou_solutie.add(jPanel40, gridBagConstraints);

        getContentPane().add(panou_solutie, "card5");

        panou_cum.setBackground(new java.awt.Color(255, 255, 255));
        panou_cum.setLayout(new java.awt.GridBagLayout());

        cum_nume.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        cum_nume.setForeground(new java.awt.Color(102, 0, 102));
        cum_nume.setText("cum Nume Prenume?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panou_cum.add(cum_nume, gridBagConstraints);

        jScrollPane4.setMinimumSize(new java.awt.Dimension(1100, 320));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(1100, 370));

        cum_demonstratie.setEditable(false);
        cum_demonstratie.setColumns(20);
        cum_demonstratie.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        cum_demonstratie.setRows(5);
        jScrollPane4.setViewportView(cum_demonstratie);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        panou_cum.add(jScrollPane4, gridBagConstraints);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/expertus_mic_mic.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panou_cum.add(jLabel21, gridBagConstraints);

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/back_back.png"))); // NOI18N
        jLabel22.setText("Inapoi");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        panou_cum.add(jLabel22, gridBagConstraints);

        getContentPane().add(panou_cum, "card7");

        panou_fara_rezultate.setBackground(new java.awt.Color(255, 255, 255));
        panou_fara_rezultate.setLayout(new java.awt.GridBagLayout());

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 72)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 51, 0));
        jLabel20.setText("Hmmm...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panou_fara_rezultate.add(jLabel20, gridBagConstraints);

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel24.setText("poate ai noroc la alta serie");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panou_fara_rezultate.add(jLabel24, gridBagConstraints);

        revinoLaMeniu.setBackground(new java.awt.Color(153, 0, 153));
        revinoLaMeniu.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        revinoLaMeniu.setForeground(new java.awt.Color(255, 255, 255));
        revinoLaMeniu.setText("revino la meniul principal");
        revinoLaMeniu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revinoLaMeniuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        panou_fara_rezultate.add(revinoLaMeniu, gridBagConstraints);

        jPanel42.setBackground(new java.awt.Color(255, 255, 255));
        jPanel42.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        panou_fara_rezultate.add(jPanel42, gridBagConstraints);

        getContentPane().add(panou_fara_rezultate, "card8");

        panou_de_ce.setBackground(new java.awt.Color(255, 255, 255));
        panou_de_ce.setLayout(new java.awt.GridBagLayout());

        jScrollPane5.setMinimumSize(new java.awt.Dimension(1100, 370));
        jScrollPane5.setPreferredSize(new java.awt.Dimension(1100, 370));

        text_de_ce.setColumns(20);
        text_de_ce.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        text_de_ce.setRows(5);
        jScrollPane5.setViewportView(text_de_ce);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        panou_de_ce.add(jScrollPane5, gridBagConstraints);

        jLabel28.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 0, 153));
        jLabel28.setText("Istoric");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        panou_de_ce.add(jLabel28, gridBagConstraints);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/search_logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panou_de_ce.add(jLabel29, gridBagConstraints);

        jLabel30.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/back_back.png"))); // NOI18N
        jLabel30.setText("inapoi");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        panou_de_ce.add(jLabel30, gridBagConstraints);

        getContentPane().add(panou_de_ce, "card9");

        panou_afiseaza_fapte.setBackground(new java.awt.Color(255, 255, 255));
        panou_afiseaza_fapte.setLayout(new java.awt.GridBagLayout());

        jScrollPane6.setMinimumSize(new java.awt.Dimension(1100, 370));
        jScrollPane6.setPreferredSize(new java.awt.Dimension(1100, 370));

        text_afiseaza_fapte.setColumns(20);
        text_afiseaza_fapte.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        text_afiseaza_fapte.setForeground(new java.awt.Color(224, 128, 237));
        text_afiseaza_fapte.setRows(5);
        jScrollPane6.setViewportView(text_afiseaza_fapte);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        panou_afiseaza_fapte.add(jScrollPane6, gridBagConstraints);

        jLabel31.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(153, 0, 153));
        jLabel31.setText("Faptele din baza de cunostinte");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        panou_afiseaza_fapte.add(jLabel31, gridBagConstraints);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/afisare_fapte_log.JPG"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panou_afiseaza_fapte.add(jLabel32, gridBagConstraints);

        jLabel33.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exempluinterfataprolog/back_back.png"))); // NOI18N
        jLabel33.setText("inapoi");
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        panou_afiseaza_fapte.add(jLabel33, gridBagConstraints);

        getContentPane().add(panou_afiseaza_fapte, "card9");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fisierConstrangeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fisierConstrangeriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fisierConstrangeriActionPerformed

    private void alegeFisierConstrangeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alegeFisierConstrangeriActionPerformed
        alegeFisier(fisierConstrangeri);
    }//GEN-LAST:event_alegeFisierConstrangeriActionPerformed

    private void fisierReguliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fisierReguliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fisierReguliActionPerformed

    private void fisierDescrieriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fisierDescrieriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fisierDescrieriActionPerformed

    private void alegeFisierDescrieriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alegeFisierDescrieriActionPerformed
        alegeFisier(fisierDescrieri);
    }//GEN-LAST:event_alegeFisierDescrieriActionPerformed

    private void alegeFisierReguliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alegeFisierReguliActionPerformed
        alegeFisier(fisierReguli);
    }//GEN-LAST:event_alegeFisierReguliActionPerformed

    private void incarcaToateFisiereleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incarcaToateFisiereleActionPerformed
        FereastraMea.AFISAT_SOLUTII = false;
        String fr = fisierReguli.getText();
        String fc = fisierConstrangeri.getText();
        String fd = fisierDescrieri.getText();
        fisierReguli.setEnabled(false);
        fisierConstrangeri.setEnabled(false);
        fisierDescrieri.setEnabled(false);
        alegeFisierReguli.setEnabled(false);
        alegeFisierDescrieri.setEnabled(false);
        alegeFisierConstrangeri.setEnabled(false);
        String dir = System.getProperty("user.dir");
        dir = dir.replace("\\", "/");
        try {
            conexiune.expeditor.trimiteMesajSicstus("director('" + dir + "')");
            conexiune.expeditor.trimiteMesajSicstus("incarca(" + fr + ", " + fc + ", " + fd + ")");
            rezolvaTestul.setEnabled(true);
        } catch (InterruptedException ex) {
            Logger.getLogger(FereastraMea.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_incarcaToateFisiereleActionPerformed

    private void saIncepemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saIncepemActionPerformed
        removeAllPanels();

        try {
            conexiune.expeditor.trimiteMesajSicstus("comanda(consulta)");
            this.add(panou_intrebare);
            this.repaint();
            this.revalidate();
        } catch (InterruptedException ex) {
            Logger.getLogger(FereastraMea.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saIncepemActionPerformed

    private void rezolvaTestulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rezolvaTestulActionPerformed
        removeAllPanels();
        
        this.add(Expertino);
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_rezolvaTestulActionPerformed

    private void afiseaza_rezultateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afiseaza_rezultateActionPerformed
        removeAllPanels();
        
        this.add(panou_solutie);
        this.repaint();
        this.revalidate();
        
        afiseazaDetaliiSolutie(solutieAfisata);
        previous.setEnabled(false);
        if(solutii.size() == 1)
            next.setEnabled(false);
        else next.setEnabled(true);
    }//GEN-LAST:event_afiseaza_rezultateActionPerformed

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        if(next.isEnabled())
        {
            previous.setEnabled(true);
            if(solutieAfisata < solutii.size() - 1)
                solutieAfisata ++;
            afiseazaDetaliiSolutie(solutieAfisata);

            if(solutieAfisata == solutii.size() - 1)
                next.setEnabled(false);
        }
    }//GEN-LAST:event_nextMouseClicked

    private void previousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousMouseClicked
        if(previous.isEnabled())
        {
            next.setEnabled(true);
            if(solutieAfisata > 0)
                solutieAfisata--;
            afiseazaDetaliiSolutie(solutieAfisata);

            if(solutieAfisata == 0)
                previous.setEnabled(false);
        }
    }//GEN-LAST:event_previousMouseClicked

    private void cumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cumActionPerformed
        String numeSolutie = solutii.get(solutieAfisata).nume;
        
        try {
            conexiune.expeditor.trimiteMesajSicstus("cum('\\'" + numeSolutie + "\\'')");
        } catch (InterruptedException ex) {
            Logger.getLogger(FereastraMea.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cumActionPerformed

    
    
    public void setCum(String descriere) 
    {
        String numeSolutie = solutii.get(solutieAfisata).nume;
        
        removeAllPanels();
        this.add(panou_cum);
        cum_nume.setText("Cum " + numeSolutie + "?");
        cum_demonstratie.setText(descriere);
        cum_demonstratie.setCaretPosition(0);
        this.repaint();
        this.revalidate();
    }
    
    public void setDeCe(String descriere) 
    {
        //String numeSolutie = solutii.get(solutieAfisata).nume;
        
        removeAllPanels();
        this.add(panou_de_ce);
        text_de_ce.setText(descriere);
        text_de_ce.setCaretPosition(0);
        this.repaint();
        this.revalidate();
    }
    
    public void setFapte(String fapte) 
    {
        //String numeSolutie = solutii.get(solutieAfisata).nume;
        
        removeAllPanels();
        this.add(panou_afiseaza_fapte);
        text_afiseaza_fapte.setText(fapte);
        text_afiseaza_fapte.setCaretPosition(0);
        this.repaint();
        this.revalidate();
    }
    
    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        removeAllPanels();
        this.add(panou_solutie);
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_jLabel22MouseClicked

    private void refaTestulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refaTestulActionPerformed
        try {
            conexiune.expeditor.trimiteMesajSicstus("comanda(reinitiaza)");
        } catch (InterruptedException ex) {
            Logger.getLogger(FereastraMea.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        fisierReguli.setEnabled(true);
        fisierConstrangeri.setEnabled(true);
        fisierDescrieri.setEnabled(true);
        alegeFisierReguli.setEnabled(true);
        alegeFisierDescrieri.setEnabled(true);
        alegeFisierConstrangeri.setEnabled(true);
        rezolvaTestul.setEnabled(false);
        
        removeAllPanels();
        this.add(Start);
        this.repaint();
        this.revalidate();
        
        solutieAfisata = 0;
        Fereastra.AFISAT_SOLUTII = false;
    }//GEN-LAST:event_refaTestulActionPerformed

    private void revinoLaMeniuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revinoLaMeniuActionPerformed
        fisierReguli.setEnabled(true);
        fisierConstrangeri.setEnabled(true);
        fisierDescrieri.setEnabled(true);
        alegeFisierReguli.setEnabled(true);
        alegeFisierDescrieri.setEnabled(true);
        alegeFisierConstrangeri.setEnabled(true);
        rezolvaTestul.setEnabled(false);
        
        removeAllPanels();
        this.add(Start);
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_revinoLaMeniuActionPerformed

    private void adaugaFactorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adaugaFactorMouseClicked
        intervalFactor.setEnabled(true);
    }//GEN-LAST:event_adaugaFactorMouseClicked

    private void iesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iesireActionPerformed
        try {
            conexiune.expeditor.trimiteSirSicstus("reinitiaza");
            conexiune.expeditor.trimiteMesajSicstus("comanda(reinitiaza)");
        } catch (InterruptedException ex) {
            Logger.getLogger(FereastraMea.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        fisierReguli.setEnabled(true);
        fisierConstrangeri.setEnabled(true);
        fisierDescrieri.setEnabled(true);
        alegeFisierReguli.setEnabled(true);
        alegeFisierDescrieri.setEnabled(true);
        alegeFisierConstrangeri.setEnabled(true);
        rezolvaTestul.setEnabled(false);
        
        removeAllPanels();
        this.add(Start);
        panou_intrebare.repaint();
        panou_intrebare.revalidate();
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_iesireActionPerformed

    private void de_ce_logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_de_ce_logoMouseClicked
        try {
            conexiune.expeditor.trimiteSirSicstus("de_ce");
        } catch (InterruptedException ex) {
            Logger.getLogger(FereastraMea.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_de_ce_logoMouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        removeAllPanels();
        this.add(panou_intrebare);
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        removeAllPanels();
        this.add(panou_solutie);
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_jLabel33MouseClicked

    private void fapteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fapteActionPerformed
        try {
            conexiune.expeditor.trimiteMesajSicstus("comanda(afiseaza_fapte)");
        } catch (InterruptedException ex) {
            Logger.getLogger(FereastraMea.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fapteActionPerformed
    
    private void alegeFisier(JTextField cmp)
    {
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        if(f != null)
        {
            String denumire = f.getAbsolutePath(); 
            cmp.setText(denumire);
        }
    }
    
    private void afiseazaDetaliiSolutie(int solutieAfisata)
    {
        Solutie sol = solutii.get(solutieAfisata);
        nume.setText(sol.nume);
        factorCertitudine.setText(sol.factorCertitudine + "%");
        descriere_solutie.setText(sol.descriere);
        
        descriere_solutie.setCaretPosition(0);
        
        icon.setIcon(new ImageIcon(sol.URL));
        
        Double gr = Double.parseDouble(sol.proprietati.get("grupa"));
        Double vst = Double.parseDouble(sol.proprietati.get("varsta"));
        
        grupa.setText(String.valueOf(gr.intValue()));
        varsta.setText(String.valueOf(vst.intValue()));
        zodie.setText(sol.proprietati.get("zodie"));
        hobby.setText(sol.proprietati.get("hobby"));
    }
    
    public void setConexiune(ConexiuneProlog _conexiune) 
    {
        conexiune =_conexiune;
    }
    
    public void setIntrebare(String intreb){
        text_intrebare.setText(intreb.substring(1, intreb.length() - 1));
        text_intrebare.setCaretPosition(0);
        panou_intrebare.repaint();
    }
    
     public void setOptiuni(String optiuni){
        intervalFactor.setEnabled(false);
        intervalFactor.setValue(100);
        this.variante.removeAll();
        this.variante.setLayout(new BoxLayout(this.variante, BoxLayout.PAGE_AXIS));
        optiuni=optiuni.trim();
        optiuni=optiuni.substring(1, optiuni.length()-1);
        optiuni=optiuni.trim();
        String[] vect_opt=optiuni.split(";");
        
        ButtonGroup grup = new ButtonGroup();
        for (final String item : vect_opt) {
            final String aux;
            if(item.charAt(0) == '\'' && item.charAt(item.length() - 1) == '\'')
                aux = item.substring(1, item.length() - 1);
            else
                aux = item;
           
            
            
            JRadioButton b = new JRadioButton("<html><body style='width:800; word-wrap:break-word'><p>" + aux + "</p></body></html>");
            b.setBackground(Color.white);
            b.setFont(new Font("Arial Rounded mt bold", 0, 28));
            b.setIcon(new ImageIcon("unchecked.png", ""));
            b.setSelectedIcon(new ImageIcon("checked.png", ""));
            
            b.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                   
                    try {
                        System.out.println(item + "(fc=" + intervalFactor.getValue() + ")");
                        conexiune.expeditor.trimiteSirSicstus(item + "(fc=" + intervalFactor.getValue() + ")");
                    } catch (InterruptedException ex) {
                        Logger.getLogger(FereastraMea.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                            
            });
            grup.add(b);
            this.variante.add(b);
        }
        
        
        this.variante.repaint();
        this.variante.revalidate();
        this.revalidate();
        this.repaint();
        
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() { 
                jScrollPane1.getVerticalScrollBar().setValue(0);
            }
        });

    }  

     public void adaugaSolutie(String solutie){  
        if(!Fereastra.AFISAT_SOLUTII)
        {
            removeAllPanels();
            
            if(solutie.equals("nu"))
            {
                this.add(panou_fara_rezultate);
                this.repaint();
                this.revalidate();
                return;
            }
           
            this.add(panou_rezultat);
            this.repaint();
            this.revalidate();
            solutii = new ArrayList<>();
            Fereastra.AFISAT_SOLUTII = true;
        } 
        
        if(solutie.equals("gata"))
        {
            numar_rezultate.setText(String.valueOf(solutii.size()));
            System.out.println(solutii.size());
            this.repaint();
            this.revalidate();
            return;
        }
        
        String[] valori = solutie.split("\\$");
        for(String aux:valori)
        {
            System.out.println(aux);
        }
        String[] proprietati = valori[3].substring(1, valori[3].length() - 1).split("%");
        
        Map<String, String> colectie = new HashMap<>();
        for(String pereche : proprietati)
        {
            String [] elemente = pereche.split("#");
            colectie.put(elemente[0], elemente[1]);
        }
        
        Solutie sol = new Solutie(valori[0], valori[1], valori[2], colectie, valori[4]);
        solutii.add(sol);
    } 
     
     
     private void removeAllPanels()
     {
         for(JPanel p : pagini)
        {
            this.remove(p);
        }
     }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FereastraMea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FereastraMea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FereastraMea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FereastraMea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FereastraMea("CTI isi da intalniri").setVisible(true);
            }
        });
    }

    public static boolean AFISAT_SOLUTII=false;
    private List<javax.swing.JPanel> pagini;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Expertino;
    private javax.swing.JPanel Start;
    private javax.swing.JLabel adaugaFactor;
    private javax.swing.JButton afiseaza_rezultate;
    private javax.swing.JButton alegeFisierConstrangeri;
    private javax.swing.JButton alegeFisierDescrieri;
    private javax.swing.JButton alegeFisierReguli;
    private javax.swing.JButton cum;
    private javax.swing.JTextArea cum_demonstratie;
    private javax.swing.JLabel cum_nume;
    private javax.swing.JLabel de_ce_logo;
    private javax.swing.JTextArea descriere_solutie;
    private javax.swing.JLabel factorCertitudine;
    private javax.swing.JButton fapte;
    private javax.swing.JTextField fisierConstrangeri;
    private javax.swing.JTextField fisierDescrieri;
    private javax.swing.JTextField fisierReguli;
    private javax.swing.JLabel grupa;
    private javax.swing.JLabel hobby;
    private javax.swing.JLabel icon;
    private javax.swing.JButton iesire;
    private javax.swing.JButton incarcaToateFisierele;
    private javax.swing.JSpinner intervalFactor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel next;
    private javax.swing.JLabel numar_rezultate;
    private javax.swing.JLabel nume;
    private javax.swing.JPanel panou_afiseaza_fapte;
    private javax.swing.JPanel panou_cum;
    private javax.swing.JPanel panou_de_ce;
    private javax.swing.JPanel panou_fara_rezultate;
    private javax.swing.JPanel panou_intrebare;
    private javax.swing.JPanel panou_rezultat;
    private javax.swing.JPanel panou_solutie;
    private javax.swing.JLabel previous;
    private javax.swing.JButton refaTestul;
    private javax.swing.JButton revinoLaMeniu;
    private javax.swing.JButton rezolvaTestul;
    private javax.swing.JButton saIncepem;
    private javax.swing.JLabel status_rezultat;
    private javax.swing.JTextArea text_afiseaza_fapte;
    private javax.swing.JTextArea text_de_ce;
    private javax.swing.JTextArea text_intrebare;
    private javax.swing.JPanel variante;
    private javax.swing.JLabel varsta;
    private javax.swing.JLabel zodie;
    // End of variables declaration//GEN-END:variables
   
}